tenk:
  filing-itemization-service-specification:
    host: "localhost"
    port: "8000"
    path: "api/internal/tenk/process-html-filing-url"
  ticker-map:
    2021AAPL: "https://www.sec.gov/Archives/edgar/data/320193/000032019322000108/0000320193-22-000108.txt"
    2021VZ: "https://www.sec.gov/Archives/edgar/data/732712/000073271222000008/0000732712-22-000008.txt"
    2021UNH: "https://www.sec.gov/Archives/edgar/data/731766/000073176622000008/0000731766-22-000008.txt"
    2020AAPL: "https://www.sec.gov/Archives/edgar/data/320193/000032019321000105/0000320193-21-000105.txt"
    2020WMT: "https://www.sec.gov/Archives/edgar/data/104169/000010416921000033/0000104169-21-000033.txt"
    2019MSFT: "https://www.sec.gov/Archives/edgar/data/789019/000156459020034944/0001564590-20-034944.txt"
    2019AXP: "https://www.sec.gov/Archives/edgar/data/4962/000000496220000030/0000004962-20-000030.txt"
  filing-item-to-part-number:
    item1: "part1"
    item1a: "part1"
    item1b: "part1"
    item2: "part1"
    item3: "part1"
    item4: "part1"
    item5: "part2"
    item6: "part2"
    item7: "part2"
    item7a: "part2"
    item8: "part2"
    item9: "part2"
    item9a: "part2"
    item9b: "part2"
    item9c: "part2"
    item10: "part3"
    item11: "part3"
    item12: "part3"
    item13: "part3"
    item14: "part3"
    item15: "part4"
    item16: "part4"
    signatures: "part4"
  stored-item-name-suffix:
    html: "_html"
    text: "_text"
    json: "_json"
hbase:
  zookeeper:
    quorum: "hbase-docker"
    property:
      clientPort: "2181"
ozone:
  om:
    host: "localhost"
    port: "9878"
    volume-name: "s3v"
    bucket-name: "tenk-filing"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
